## Test configuration

nick: Default_bot
username: non_sei_il_benvenuto
ircname: Matteo
lib:
    - poe-component-irc-plugin-rekarma/lib

networks:
    freenode:
        server: chat.freenode.net
        local_plugins:
            - [Connector, { reconnect: 30 } ]
            - [AutoJoin, {
                Channels: [
                    '##dipreathon',
                ]
            }]
            - [ReKarma]
            - [Logger, { Path: /usr/src/app/logs }]
